import type { CardScript } from "@fyendal/engine";

// Audited sources whose on-hit text watches an attack they did not make.
// All other onHit scripts run only for their own attack.
export const friendlyHitSourceKeys: ReadonlySet<string> = new Set([
  "a bit off the side|1",
  "amulet of assertiveness|2",
  "arakni, black widow|0",
  "arakni, funnel web|0",
  "arakni, marionette|0",
  "arakni, tarantula|0",
  "arakni, web of deceit|0",
  "avast ye!|3",
  "beckon steel|3",
  "beckoning light|1",
  "below the belt|1",
  "benji, the piercing wind|0",
  "blizzard bolt|1",
  "blizzard bolt|2",
  "blizzard bolt|3",
  "bloodspill invocation|1",
  "bloodspill invocation|2",
  "bloodspill invocation|3",
  "boom grenade|1",
  "boom grenade|2",
  "boom grenade|3",
  "breeze rider boots|0",
  "briar, warden of thorns|0",
  "briar|0",
  "burn up // shock|1",
  "buzz bolt|1",
  "buzz bolt|2",
  "buzz bolt|3",
  "carve up|2",
  "chill to the bone|1",
  "chill to the bone|2",
  "chill to the bone|3",
  "chilling icevein|1",
  "chilling icevein|2",
  "chilling icevein|3",
  "cindra, dracai of retribution|0",
  "cindra|0",
  "cleave|1",
  "concealed blade|3",
  "dice up|3",
  "dig for souls|1",
  "dorinthea ironsong|0",
  "dorinthea|0",
  "drop the anchor|1",
  "eclipse existence|3",
  "electrify|1",
  "electrify|2",
  "electrify|3",
  "fang, dracai of blades|0",
  "fang|0",
  "glistening steelblade|2",
  "grains of bloodspill|0",
  "hack to reality|2",
  "hala goldenhelm|0",
  "heave ho!|3",
  "high striker|1",
  "high striker|2",
  "high striker|3",
  "ice quake|1",
  "ice quake|2",
  "ice quake|3",
  "imperial seal of command|1",
  "kassai, cintari sellsword|0",
  "katsu, the wanderer|0",
  "katsu|0",
  "lace with bloodrot|1",
  "lace with frailty|1",
  "lace with inertia|1",
  "legacy of ikaru|3",
  "livewire press|1",
  "loot the arsenal|3",
  "loot the hold|3",
  "lumina ascension|2",
  "mark of neverest|3",
  "mark of pathstone|3",
  "mark of ushering|3",
  "mask of momentum|0",
  "mask of perdition|0",
  "mask of the pouncing lynx|0",
  "minerva themis|0",
  "nature's path pilgrimage|1",
  "nature's path pilgrimage|2",
  "nature's path pilgrimage|3",
  "ode to wrath|2",
  "okana scar wraps|0",
  "outland skirmish|1",
  "outland skirmish|2",
  "outland skirmish|3",
  "plunder run|1",
  "plunder run|2",
  "plunder run|3",
  "poison the tips|2",
  "poisoned blade|1",
  "poisoned blade|2",
  "poisoned blade|3",
  "pummel|1",
  "pummel|2",
  "pummel|3",
  "refraction bolters|0",
  "regain composure|3",
  "scar tissue|1",
  "sense weakness|3",
  "settle the bill|1",
  "sharpening sparks|1",
  "shatter the weakpoint|1",
  "shock charmers|0",
  "slice up|1",
  "smashing good time|1",
  "smashing good time|2",
  "smashing good time|3",
  "spike with bloodrot|1",
  "spike with frailty|1",
  "spike with inertia|1",
  "spoils of war|1",
  "steel to the dome|1",
  "target totalizer|0",
  "tear asunder|3",
  "toxic tips|0",
  "two sides to the blade|1",
  "undead grasp|0",
  "vest of the first fist|0",
  "yo ho ho!|3",
]);

export function withFriendlyHitScope(key: string, script: CardScript): CardScript {
  if (!friendlyHitSourceKeys.has(key)) return script;
  if (!script.onHit) throw new Error(`friendly hit source "${key}" has no onHit hook`);
  return { ...script, onHitScope: "friendly" };
}
